In [1]:
import numpy as np
import cv2
import pandas as pd

In [7]:
im=cv2.imread(r"E:\photos\11.jpg")   #taken image as input
im2=cv2.resize(im,(720,720))         #resize image according to comfortability
im2=im2/255                          #normalize the image
im2=np.array(im2)                    #convert image in numpy array for operations
r1=(im2[:,:,0])                      #taken out R from RBG because its 3d dimensional
r2=(im2[:,:,1])                      #taken out R from RBG because its 3d dimensional
r3=(im2[:,:,2])                      #taken out R from RBG because its 3d dimensional
shape=im2.shape

(720, 720, 3)


In [22]:
kernel=np.array([[0,-1,0],[-1,5,-1],[0,-1,0]])        #DEFINE kernel to apply on image for shapening
ed1=[]                                                #three different list to store value where kernel or filter is applied
ed2=[]
ed3=[]

#---------------applied filter on all three lists------------------------

for i in range(0,shape[0]-2):
    for j in range(0,shape[1]-2):
        ed1.append(r1[i][j]*kernel[0][0]+r1[i][j+1]*kernel[0][1]+r1[i][j+2]*kernel[0][2]+
                  r1[i+1][j]*kernel[1][0]+r1[i+1][j+1]*kernel[1][1]+r1[i+1][j+2]*kernel[1][2]+
                  r1[i+2][j]*kernel[2][0]+r1[i+2][j+1]*kernel[2][1]+r1[i+2][j+2]*kernel[2][2])
for i in range(0,shape[0]-2):
    for j in range(0,shape[1]-2):
        ed2.append(r2[i][j]*kernel[0][0]+r2[i][j+1]*kernel[0][1]+r2[i][j+2]*kernel[0][2]+
                  r2[i+1][j]*kernel[1][0]+r2[i+1][j+1]*kernel[1][1]+r2[i+1][j+2]*kernel[1][2]+
                  r2[i+2][j]*kernel[2][0]+r2[i+2][j+1]*kernel[2][1]+r2[i+2][j+2]*kernel[2][2])
for i in range(0,shape[0]-2):
    for j in range(0,shape[1]-2):
        ed3.append(r3[i][j]*kernel[0][0]+r3[i][j+1]*kernel[0][1]+r3[i][j+2]*kernel[0][2]+
                  r3[i+1][j]*kernel[1][0]+r3[i+1][j+1]*kernel[1][1]+r3[i+1][j+2]*kernel[1][2]+
                  r3[i+2][j]*kernel[2][0]+r3[i+2][j+1]*kernel[2][1]+r3[i+2][j+2]*kernel[2][2])


ed1=np.array(ed1)                  #convert lists intonumpy array to apply further operations
ed1=ed1.reshape(1,len(ed1))        #reshape it into 2d (1,len(ed1))

ed2=np.array(ed2)
ed2=ed2.reshape(1,len(ed2))

ed3=np.array(ed3)
ed3=ed3.reshape(1,len(ed3))

In [38]:

new=np.concatenate((ed1,ed2,ed3),axis=0)                   #now concatenate or merge all three arrays in one  
new=new.T                                         #take transpose of new to get 3 layered arrayed like in rbg but still its in 2d
new_image=new.reshape(718,718,3)                  #convert from 2d to 3d
cv2.imshow("sharpen 3d image using kernel",new_image)     #sharpen image is formed
cv2.waitKey(0)

[[[ 0.03921569  0.62352941  0.68627451]
  [ 1.01176471  0.85882353  0.75294118]
  [-0.27843137 -0.12941176  0.07843137]
  ...
  [ 0.25490196  0.16862745  0.1372549 ]
  [ 0.18431373  0.19607843  0.18039216]
  [ 0.23529412  0.18823529  0.20392157]]

 [[ 0.34901961  0.78431373  0.84705882]
  [ 1.17647059  0.91764706  0.81176471]
  [-0.14901961 -0.1372549   0.20392157]
  ...
  [ 0.2745098   0.19215686  0.16078431]
  [ 0.23921569  0.22352941  0.21568627]
  [ 0.17647059  0.15294118  0.13333333]]

 [[ 0.03921569  0.07843137 -0.12156863]
  [-0.16470588 -0.21568627 -0.20392157]
  [ 0.25490196  0.23137255  0.58823529]
  ...
  [ 0.2745098   0.19215686  0.16078431]
  [ 0.20784314  0.19607843  0.18823529]
  [ 0.21176471  0.18431373  0.17647059]]

 ...

 [[ 0.23137255  0.21568627  0.28627451]
  [ 0.25098039  0.23529412  0.30980392]
  [ 0.28627451  0.27058824  0.34509804]
  ...
  [ 0.27843137  0.24313725  0.30196078]
  [ 0.27843137  0.21568627  0.30196078]
  [ 0.22352941  0.23921569  0.2745098 ]]

 [

-1